apiVersion: v1
kind: Service
metadata:
  name: pulsenet-gateway
  labels:
    app.kubernetes.io/name: pulsenet-gateway
    app.kubernetes.io/instance: echo-stack
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pulsenet-gateway
    app.kubernetes.io/instance: echo-stack
  ports:
    - name: http
      port: 80
      targetPort: 8080
