apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-api-config
  labels:
    app.kubernetes.io/name: echo-api
    app.kubernetes.io/instance: echo-stack
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: echo-stack
data:
  ECHO_ENV: production
  LOG_LEVEL: info
  FEATURE_FLAGS__ENABLE_PULSE_STREAM: "true"
  FEATURE_FLAGS__ENABLE_ORBITAL_WATCHDOG: "false"
