apiVersion: v1
kind: Secret
metadata:
  name: echo-api-secrets
  labels:
    app.kubernetes.io/name: echo-api
    app.kubernetes.io/instance: echo-stack
    app.kubernetes.io/component: api
type: Opaque
stringData:
  DATABASE_URL: postgresql://echo:echo@postgres/echo
  JWT_SECRET_KEY: changeme
