apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-stack.fullname" . }}-grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
  ports:
    - name: http
      port: 3000
      targetPort: http
