apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-stack.fullname" . }}-otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
    app.kubernetes.io/component: observability
spec:
  replicas: {{ .Values.observability.otelCollector.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
      app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otel-collector
        app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
    spec:
      containers:
        - name: otel-collector
          image: {{ .Values.observability.otelCollector.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - "--config=/etc/otelcol/otel-collector.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 9464
              name: prom-exporter
            - containerPort: 8888
              name: telemetry
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
      volumes:
        - name: config
          configMap:
            name: {{ include "echo-stack.fullname" . }}-otel-config
            items:
              - key: otel-collector.yaml
                path: otel-collector.yaml
