apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "echo-stack.fullname" . }}-otel-config
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
data:
  otel-collector.yaml: |
{{ (.Files.Get "files/observability/otel-collector.yaml") | indent 4 }}
