apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-stack.fullname" . }}-otel-collector
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: prom-exporter
      port: 9464
      targetPort: prom-exporter
    - name: telemetry
      port: 8888
      targetPort: telemetry
