apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-stack.fullname" . }}-prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: {{ include "echo-stack.fullname" . }}
  ports:
    - name: http
      port: 9090
      targetPort: http
