apiVersion: v1
kind: Service
metadata:
  name: atlas-core
  labels:
    app.kubernetes.io/name: atlas-core
    app.kubernetes.io/instance: echo-stack
    app.kubernetes.io/component: atlas
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atlas-core
    app.kubernetes.io/instance: echo-stack
  ports:
    - name: grpc
      port: 9100
      targetPort: 9100
    - name: http
      port: 9101
      targetPort: 9101
